---@class JosephMcKean.lib.mod
---@field name string
--
---@class JosephMcKean.lib.keybind
---@field keyCode integer
---@field isShiftDown boolean
---@field isAltDown boolean
---@field isControlDown boolean
--
---@class JosephMcKean.lib.size
---@field width integer
---@field height integer
--
---@class JosephMcKean.lib.rgb
---@field r number
---@field g number
---@field b number
