---@class JosephMcKean.lib.mod
---@field name string
--
---@class JosephMcKean.lib.keybind
---@field keyCode integer
---@field isShiftDown boolean
---@field isAltDown boolean
---@field isControlDown boolean
--
---@class JosephMcKean.lib.size
---@field width integer
---@field height integer
